### ISSUE TITLE
GP模型部署

### ISSUE THREAD

**Issue by Lijiadong** [xhw205/Efficient-GlobalPointer-torch#1]
请教一下部署的时候如何进行加速的？是用TensorRT吗？

**Comment by xhw205** [comment]
最终是用lstm做embedding占得显存也比较小，封装给flask，没做加速

**Comment by Lijiadong** [comment]
“用lstm做embedding”这个没有理解，希望不吝赐教！

**Comment by xhw205** [comment]
就是简单的把 bert  换成 bilstm，bert 推理太慢了

**Comment by Lijiadong** [comment]
感谢解答！相比bert f1效果掉点多少啊

**Comment by xhw205** [comment]
用我们自己的数据集，比bert-base掉了2%多点。

词表是自己建的，没有用词向量预训练，就纯 nn.embeding + Bilstm ，train from scrath，
用的时候选了个recall高的，然后再卡规则

**Comment by xxllp** [comment]
不知道楼主有尝试其他算法模型 吗  这个效果算最好的吗

**Comment by xhw205** [comment]
token-pair 范式下的NER 都大差不差，不一定最优，但一定是主流

**Comment by xxllp** [comment]
你这个可以做关系抽取的吗
