### ISSUE TITLE
f1的计算是可以近似平均的么?

### ISSUE THREAD

**Issue by nickyi1990** [xhw205/Efficient-GlobalPointer-torch#2]
```python
f1, p, r = metrics.get_evaluate_fpr(logits, labels)
total_f1_ += f1
```

这两行代码算的total_f1是近似的吧~, 平均所有batch的f1和计算一个epoch的整个f1还是有差距的

**Comment by xhw205** [comment]
谢谢提醒~
这里eval主要就是验证下选个较优模型。如果是发paper做对比实验，还是需要严格将整个epoch的pred_list 和 true_list去算F1
