### ISSUE TITLE
Pedict_cme预测结果变化

### ISSUE THREAD

**Issue by Pudding023** [xhw205/Efficient-GlobalPointer-torch#5]
根据天池比赛数据格式修改了我的数据，修改了ent2id字典，选用的roberta_wwm_base,train_cme跑了5遍，输出日志显示结果良好，f1score达到70+，然后运行predict_cme进行预测时，得到score的矩阵每跑一次都在变化。是哪里没改还是有bug?

**Comment by Pudding023** [comment]
很难受

**Comment by Pudding023** [comment]
就差最后一步，很难受🌚🌚

**Comment by xhw205** [comment]
1、项目的预测输出仅用作CBLUE天池打榜参考，custom dataset请自行debug
2、请自行了解GitHub-Issue正确提问方式，不要重复open无意义的issue
