### ISSUE TITLE
请教代码问题

### ISSUE THREAD

**Issue by SCU-JJkinging** [xhw205/Efficient-GlobalPointer-torch#6]
![image](https://user-images.githubusercontent.com/59439162/173504899-5a5a0ba2-9f66-4583-965b-51b55fde2d19.png)
请问这个BertAdam是哪来的呢？

**Comment by fade-color** [comment]
[class BertAdam(Optimizer):](https://github.com/xhw205/Efficient-GlobalPointer-torch/blob/11c037c1dab9c7b4e87025eaae9f88c4d61e172a/utils/bert_optimization.py#L183)
